[owner]
	name = Bai Ivan
	organization = Bla-Bla-org

[settings]
	config = 1
	set_a = a
	set_b = b

[database]
; use IP address in case network name resolution is not working
	server = 192.0.2.55    
	port = 143
	file = "payroll_bla.dat"

